# Site settings
title: N3RO
email: nero98@sfr.fr
url: https://github.com/N3ROO/n3roo.github.io
# Google search engine description
description: "Lilian Gallon, as known as N3RO is a game and software developer. Studied at the University of Bordeaux, and is currently finishing his second year of studies."
# Keywords for google search, separated by commas
keywords: "Lilian, Gallon, IUT Bordeaux, Bordeaux, Developer, Game,"
skills: "Game & software developer"
meta_author: Lilian Gallon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: n3ro

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: N3RO, Lilian Gallon
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/8811838/n3ro
  - title: github
    url: https://github.com/N3ROO/

# Postal address (add as many lines as necessary)
address:
  - line: University of Bordeaux,
  - line: IUT Informatique

# Credits content
credits: 'Powered by <a href="https://github.com">Github</a>, and <a href="http://startbootstrap.com">Freelancer</a>.'

# Build settings
markdown: kramdown
permalink: pretty
